### ISSUE TITLE
Induced drag seems not to me modelled.

### ISSUE THREAD

**Issue by Alpakinator** [Hadiiiiiiiiiiiiii/AlexStillTalking#1]
One problem with the drag graphs and by extension, acceleration graphs is that in practice they underestimate drag / overestimate acceleration at low speed. 

It's because the calculation seems to not take into account induced drag, and to only model parasite and wave drag. At low speed induced drag is majority of the drag of the aircraft, while drag curves from "/makedraggraph" and "/maketdragthrustgraph" start from 0 kgf of drag at 0 kph. That suggests that there is no induced drag in your app. 

A more useful but much harder to do graph would be one taking induced drag at 0°AoA. The best but the hardest would be to also take into account induced drag variations due to AoA. This means taking into account positive AoA at low speed and close to zero / negative AoA at high speed. 

I have no solution to this problem and I haven't varified that it's the case, in your code.

**Comment by Hadiiiiiiiiiiiiii** [comment]
why would there be drag if the plane is going 0kph? 

the way that the bot calcualtes the drag right now is by using the source code reslesed in the [dagor engine repo](https://github.com/GaijinEntertainment/DagorEngine/blob/main/prog/gameLibs/gamePhys/common/polares.cpp) not too long ago, whether this includes Induced drag or not im not sure but i am 99% sure that this is what is used by war thundet to calculate all drag, too many other things line up for it to be wrong,
the basic formula is 
```
0.5 * airden * speed * cd * refarea
```
where cd is generated by engine the source code

**Comment by Alpakinator** [comment]
True, you're both right, both induced and parasitic drag are modelled, judging by the Cd / AoA graph. I was confused by drag graphs like this one:
![image](https://github.com/Hadiiiiiiiiiiiiii/AlexStillTalking/assets/67637851/8c3ea856-e1ec-4184-a7af-156614e25cc3)

Those kinds of graphs are made by taking into account changing of AoA to maintain level flight, while your don't. And they start from stall speed, while your assume that the plane doesn't stall (or drives on the ground). I thought that even with 0° AoA we would see a bump of drag at low speed due to high Induced drag, but that's not true. And, yeah, clearly drag should be 0 at 0 kph, I was confused.

**Comment by Hadiiiiiiiiiiiiii** [comment]
all good 👍
